/**
 * Created by ydubale on 1/20/15.
 */
public interface Protocol {

    byte OVERLAY_NODE_SENDS_REGISTRATION = 2;
    byte REGISTRY_REPORTS_REGISTRATION_STATUS = 3;

    byte REGISTRY_SENDS_NODE_MANIFEST = 4;
    byte NODE_REPORTS_OVERLAY_SETUP_STATUS = 5;

    byte REGISTRY_REQUESTS_TASK_INITIATE = 6;
    byte OVERLAY_NODE_SENDS_DATA = 7;
    byte OVERLAY_NODE_REPORTS_TASK_FINISHED = 8;

    byte REGISTRY_REQUESTS_TRAFFIC_SUMMARY = 9;
    byte OVERLAY_NODE_REPORTS_TRAFFIC_SUMMARY = 10;

}
